spring:
  application:
    name:
      mic-cataloge-service
  profiles:
    active: testdata


server:
  port: 9001
  tomcat:
    connection-timeout: 2
    keep-alive-timeout: 15
    threads:
      max: 50

bookshop:
  greeting: "Hello from config YML"

