spring:
  application:
    name:
      mic-cataloge-service
  profiles:
    active: testdata
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
  datasource:
    username: root
    password: hilg456
    url: jdbc:mysql://localhost:3306/bookshopdb_catalog
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 9001
  tomcat:
    connection-timeout: 2
    keep-alive-timeout: 15
    threads:
      max: 50

bookshop:
  greeting: "Hello from config YML"

management:
  endpoints:
    web:
      exposure:
        include: refresh