name: Commit Stage

on: push
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@3
      - name: Set up JDK
        uses: actions/setup-java@3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@414ae3ccd767c252f5661f1ace9f835f9654f2b5
      - name: Build Gradle
        run: ./gradlew build
